### ISSUE TITLE
Double loading in game start (first: game, second: reload)

### ISSUE THREAD

**Issue by AdamCalculator** [AdamCalculator/DynamicPack#53]

**Comment by HiWord9** [comment]
Had the similar issue in my mod, here is what i figured out.

U make a mixin for `ModelLoader.class` (or how it is in ur mappings) and u Inject at `<init>` somewhere after important stuff in method such as setting some ModelLoader's fields, im sure `INVOKE at Profile.push(String)` is okay. Then from this method u call all ur wanted logic.
[Here is how is calls mine.](https://github.com/HiWord9/RPRenames/blob/1.20.4/src/main/java/com/HiWord9/RPRenames/mixin/ModelLoaderMixin.java#L25)

I originally saw it in CIT Resewn, so u can check [its source](https://github.com/SHsuperCM/CITResewn/blob/main/src/main/java/shcm/shsupercm/fabric/citresewn/mixin/ModelLoaderMixin.java) too

**Comment by AdamCalculator** [comment]
fixed
