### ISSUE TITLE
1.20.1 Java can't find JSONObject

### ISSUE THREAD

**Issue by Krimatoria** [AdamCalculator/DynamicPack#57]
DynamicPack-forge-1.20-1.0.18.jar

> Exception in thread "SyncThread0" java.lang.NoClassDefFoundError: org/json/JSONObject
> 	at TRANSFORMER/dynamicpack@1.0.18/com.adamcalculator.dynamicpack.status.StatusChecker.check(StatusChecker.java:22)
> 	at TRANSFORMER/dynamicpack@1.0.18/com.adamcalculator.dynamicpack.sync.SyncThread.startSync(SyncThread.java:37)
> 	at TRANSFORMER/dynamicpack@1.0.18/com.adamcalculator.dynamicpack.sync.SyncThread.run(SyncThread.java:25)
> Caused by: java.lang.ClassNotFoundException: org.json.JSONObject
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
> 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
> 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
> 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
> 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
> 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 3 more

**Comment by AdamCalculator** [comment]
Yeah I know about that, the mod doesn't work correctly on forge

**Comment by AdamCalculator** [comment]
hmm, the problem was that the forge libraries didn't work, and now instead of org.json I use gson, and I removed other libraries too, it's worth trying to reanimate forge.... someday...

**Comment by Krimatoria** [comment]
> hmm, the problem was that the forge libraries didn't work, and now instead of org.json I use gson, and I removed other libraries too, it's worth trying to reanimate forge.... someday...

Nice))) Waiting for an update
